package rw.schoolpass.web;
import jakarta.validation.Valid; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.validation.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import rw.schoolpass.model.Student; import rw.schoolpass.repo.StudentRepository; import rw.schoolpass.service.*; import java.time.Year; import java.util.*;
@Controller public class StudentManagementController {
 private final StudentRepository repo; private final StudentService service; private final AuditService audit;
 public StudentManagementController(StudentRepository r,StudentService s,AuditService a){repo=r;service=s;audit=a;}
 @GetMapping("/students/new") String form(Model m,@RequestParam(required=false) Long edit){
  StudentForm f=new StudentForm(); f.setAcademicYear(String.valueOf(Year.now().getValue()));
  if(edit!=null){Student s=repo.findById(edit).orElseThrow();f.setStudentCode(s.getStudentCode());f.setFirstName(s.getFirstName());f.setLastName(s.getLastName());f.setClassName(s.getClassName());f.setSection(s.getSection());f.setSchoolName(s.getSchoolName());f.setPrincipalName(s.getPrincipalName());f.setAcademicYear(s.getAcademicYear());f.setFeeRequired(s.getFeeRequired());f.setFeePaid(s.getFeePaid());f.setUniformStatus(s.getUniformStatus());}
  m.addAttribute("studentForm",f);m.addAttribute("studentId",edit);m.addAttribute("org.springframework.validation.BindingResult.studentForm",new BeanPropertyBindingResult(f,"studentForm"));return "student-form";}
 @PostMapping("/students/new") String create(@Valid @ModelAttribute("studentForm") StudentForm f,BindingResult br,@RequestParam(required=false) Long edit,@RequestParam(required=false) MultipartFile photo,Authentication auth){String code=trim(f.getStudentCode()),year=trim(f.getAcademicYear()),cls=trim(f.getClassName()).toUpperCase(),stream=trim(f.getSection()).toUpperCase(); if(repo.findByStudentCodeAndAcademicYear(code,year).filter(s->!Objects.equals(s.getId(),edit)).isPresent())br.rejectValue("studentCode","duplicate","Student code already exists for this academic year."); if(f.getFeePaid()>f.getFeeRequired())br.rejectValue("feePaid","invalid","Paid amount cannot exceed required amount."); try{service.validateStream(cls,stream);}catch(Exception e){br.rejectValue("section","invalid",e.getMessage());} if(br.hasErrors())return "student-form"; Student s=edit==null?new Student():repo.findById(edit).orElseThrow();s.setStudentCode(code);s.setFirstName(trim(f.getFirstName()));s.setLastName(trim(f.getLastName()));s.setClassName(cls);s.setSection(stream);s.setSchoolName(trim(f.getSchoolName()));s.setPrincipalName(trim(f.getPrincipalName()));s.setAcademicYear(year);s.setFeeRequired(f.getFeeRequired());s.setFeePaid(f.getFeePaid());s.setFeeStatus(service.feeStatus(f.getFeeRequired(),f.getFeePaid()));s.setUniformStatus(trim(f.getUniformStatus()));if(s.getCardToken()==null)s.setCardToken(service.newToken()); if(photo!=null&&!photo.isEmpty())s.setPhotoUrl(service.savePhoto(photo)); if(s.getPhotoUrl()==null)s.setPhotoUrl("");s.setCardActive(true);s.touch();repo.save(s);audit.log(auth.getName(),edit==null?"STUDENT_CREATED":"STUDENT_UPDATED","STUDENT",String.valueOf(s.getId()),s.getStudentCode());return "redirect:/students?success="+(edit==null?"created":"updated");}
 @PostMapping("/students/{id}/replace-card") String replace(@PathVariable Long id,Authentication auth){Student s=repo.findById(id).orElseThrow();String old=s.getCardToken();s.setCardActive(false);s.setCardToken(service.newToken());s.setCardActive(true);repo.save(s);audit.log(auth.getName(),"CARD_REPLACED","STUDENT",String.valueOf(id),"Old credential deactivated; new credential issued");return "redirect:/students?success=replaced";}
 @GetMapping("/students/import") String importPage(){return "import";}
 @PostMapping("/students/import") String importCsv(@RequestParam("file") MultipartFile file,Authentication auth,Model m){int created=0,skipped=0;List<String> errors=new ArrayList<>();try(java.io.BufferedReader r=new java.io.BufferedReader(new java.io.InputStreamReader(file.getInputStream(),java.nio.charset.StandardCharsets.UTF_8))){String line=r.readLine();if(line==null)throw new IllegalArgumentException("CSV is empty.");String[] h=line.split(",",-1);Map<String,Integer> idx=new HashMap<>();for(int i=0;i<h.length;i++)idx.put(h[i].trim().toLowerCase(),i);String required="studentcode,firstname,lastname,classname,section,schoolname,principalname,academicyear,feerequired,feepaid,uniformstatus";for(String k:required.split(","))if(!idx.containsKey(k))throw new IllegalArgumentException("Missing CSV column: "+k);while((line=r.readLine())!=null){if(line.isBlank())continue;String[] c=line.split(",",-1);try{String code=c[idx.get("studentcode")].trim(),year=c[idx.get("academicyear")].trim();if(repo.findByStudentCodeAndAcademicYear(code,year).isPresent()){skipped++;continue;}String cls=c[idx.get("classname")].trim().toUpperCase(),stream=c[idx.get("section")].trim().toUpperCase();service.validateStream(cls,stream);long req=Long.parseLong(c[idx.get("feerequired")].trim()),paid=Long.parseLong(c[idx.get("feepaid")].trim());if(paid>req)throw new IllegalArgumentException("fee paid exceeds required");Student s=new Student();s.setStudentCode(code);s.setFirstName(c[idx.get("firstname")].trim());s.setLastName(c[idx.get("lastname")].trim());s.setClassName(cls);s.setSection(stream);s.setSchoolName(c[idx.get("schoolname")].trim());s.setPrincipalName(c[idx.get("principalname")].trim());s.setAcademicYear(year);s.setFeeRequired(req);s.setFeePaid(paid);s.setFeeStatus(service.feeStatus(req,paid));s.setUniformStatus(c[idx.get("uniformstatus")].trim().toUpperCase());s.setCardToken(service.newToken());s.setCardActive(true);s.setPhotoUrl("");repo.save(s);created++;}catch(Exception e){errors.add("Line "+(created+skipped+errors.size()+2)+": "+e.getMessage());}}}catch(Exception e){errors.add(e.getMessage());}audit.log(auth.getName(),"STUDENT_IMPORT","STUDENT","-","Created="+created+", skipped="+skipped);m.addAttribute("created",created);m.addAttribute("skipped",skipped);m.addAttribute("errors",errors);return "import-result";}
 private String trim(String s){return s==null?"":s.trim();}
}
